name: build

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    name: DistroKit Build
    #runs-on: ${{ vars.BUILD_RUNS_ON || (github.repository == 'rauc/meta-rauc' && 'ptx-runner') || 'ubuntu-latest' }}
    runs-on: [self-hosted, forrest, build]
    timeout-minutes: 120
    strategy:
      matrix:
        platform:
          - v7a
          - v8a
          - x86_64
          - mips
          - mipsel
          - rpi1
          - v7a_noneon
    steps:
      - name: Setup Overlay Mount for PTXdist Cache
        run: |
          ls -l /srv/cache
          sudo mkdir /srv/cache-overlay /srv/cache-work
          sudo mount -t overlay overlay -o lowerdir=/srv/cache,upperdir=/srv/cache-overlay,workdir=/srv/cache-work /srv/cache
          sudo chmod ugo+rwx /srv/cache/src
          ls -l /srv/cache
          mkdir ~/.ptxdist
          echo 'PTXCONF_SETUP_SRCDIR="/srv/cache/src"' >> ~/.ptxdist/ptxdistrc-git
          echo 'PTXCONF_SETUP_PTXMIRROR="https://www.pengutronix.de/software/ptxdist/temporary-src"' >> ~/.ptxdist/ptxdistrc-git
          cp ~/.ptxdist/ptxdistrc-git ~/.ptxdist/ptxdistrc-2010.01
      - name: Install Dependencies
        run: |
          sudo apt-get -y --no-install-recommends install python3-venv
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          ptxdist platform configs/platform-${{ matrix.platform }}/platformconfig
          ls -l
          ptxdist print PTXDIST_VERSION_FULL | tee dev-pkg-base
          readlink -f selected_platformconfig | tee -a dev-pkg-base
          readlink -f selected_toolchain | tee -a dev-pkg-base
          md5sum dev-pkg-base | cut -d ' ' -f 1 | tee dev-pkg-hash
          echo "PTXCONF_PROJECT_CREATE_DEVPKGS=y" | tee -a configs/ptxconfig
          echo "PTXCONF_PROJECT_USE_DEVPKGS=y" | tee -a configs/ptxconfig
          echo "PTXCONF_PROJECT_DEVPKGDIR=\"/srv/cache/dev-pkgs/$(cat dev-pkg-hash)\"" | tee -a configs/ptxconfig
          echo "PTXCONF_PROJECT_DEVMIRROR=\"\"" | tee -a configs/ptxconfig
          ptxdist migrate
          git diff
          ptxdist bsp-info
      - name: Build busybox
        run: |
          ptxdist targetinstall -q -j busybox
      - name: Build rauc
        run: |
          ptxdist targetinstall -q -j rauc
      - name: Build Packages
        run: |
          ptxdist go -q -j
      - name: Build Images
        run: |
          ptxdist images -q -j
      - name: Show Images
        run: |
          ls -la platform-*/images
      - name: Compress Images
        run: |
          time zstdmt --rm platform-*/images/*.img || true
          ls -la platform-*/images
      - name: Cache Data
        if: ${{ always() }}
        run: |
          echo "${{ secrets.PTXDIST_CACHE_KEY }}" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ls -l /srv/cache-overlay
          test ! -s ~/.ssh/id_ed25519 || rsync -rvx --ignore-existing /srv/cache/src ptxdist-cache: || true
          mkdir "$(cat dev-pkg-hash)"
          mv -v platform-*/packages/*-dev.tar.gz "$(cat dev-pkg-hash)/" || true
          test ! -s ~/.ssh/id_ed25519 || rsync -rvx --ignore-existing "$(cat dev-pkg-hash)" ptxdist-cache:dev-pkgs/ || true
      - name: Upload RAUC Bundle
        uses: actions/upload-artifact@v4
        with:
          name: rauc-bundle-${{ matrix.platform }}
          path: platform-*/images/update.raucb
          compression-level: 0
          retention-days: 30
